spring:
  application:
    name: timesheet-service
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
logging:
  level:
      org.springframework.cloud: DEBUG
      com.netflix.eureka: DEBUG
      com.netflix.discovery: DEBUG