server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false





#server:
#  port: 8761  # Default Eureka port
#
#spring:
#  application:
#    name: eureka-server
#  security:
#    user:
#      name: admin
#      password: eureka-secret
#
#eureka:
#  client:
#    register-with-eureka: false  # Server should not register itself
#    fetch-registry: false       # Server does not need to fetch registry
#    service-url:
#      defaultZone: http://admin:eureka-secret@localhost:8761/eureka  # Self-reference (optional)









#server:
#  port: 8761  # Default Eureka port
#
#spring:
#  application:
#    name: eureka-server
#  security:  # Optional security
#    user:
#      name: admin
#      password: eureka-secret
#
#eureka:
#  client:
#    register-with-eureka: false  # This is the server, don't register itself
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka